  server:
    port: 8081

  spring:
    datasource:
      url: jdbc:postgresql://${ORCHESTRATOR_DB_HOST:localhost}:${ORCHESTRATOR_DB_PORT:5433}/orchestrator-db
      username: ${ORCHESTRATOR_DB_USER:postgres}
      password: ${ORCHESTRATOR_DB_PASSWORD:postgres}
      driver-class-name: org.postgresql.Driver

    thymeleaf:
      enabled: true
      prefix: classpath:/templates/
      suffix: .html

    jpa:
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      generate-ddl: false
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

    application:
      name: orchestrator-service

    liquibase:
      enabled: true
      change-log: /db/changelog/db.changelog-1.0.xml

  eureka:
    client:
      serviceUrl:
        defaultZone: http://eureka:8761/eureka