version: '3.1'

services:

  orchestrator-db:
    container_name: orchestrator-db
    image: postgres:14.1-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: ${ORCHESTRATOR_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${ORCHESTRATOR_DB_PASSWORD:-postgres}
      POSTGRES_DB: orchestrator-db
    restart: always

  recognizer-db:
    container_name: recognizer-db
    image: postgres:14.1-alpine
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: ${RECOGNIZER_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${RECOGNIZER_DB_PASSWORD:-postgres}
      POSTGRES_DB: recognizer-db
    restart: always

  telegram-bot-db:
    container_name: telegram-bot-db
    image: postgres:14.1-alpine
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: ${TELEGRAM_BOT_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${TELEGRAM_BOT_DB_PASSWORD:-postgres}
      POSTGRES_DB: telegram-bot-db
    restart: always

  eureka:
    container_name: eureka
    image: nekromant322/overmoney:eureka
    ports:
      - '8761:8761'

  orchestrator:
    container_name: orchestrator
    image: nekromant322/overmoney:orchestrator
    ports:
      - '8081:8081'
    environment:
      ORCHESTRATOR_DB_USER: ${ORCHESTRATOR_DB_USER}
      ORCHESTRATOR_DB_PASSWORD: ${ORCHESTRATOR_DB_PASSWORD}
      ORCHESTRATOR_DB_HOST: ${ORCHESTRATOR_DB_HOST}
      ORCHESTRATOR_DB_PORT: ${ORCHESTRATOR_DB_PORT}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      JWT_ACCESS_KEY: ${JWT_ACCESS_KEY}
      JWT_REFRESH_KEY: ${JWT_REFRESH_KEY}
    depends_on:
      - orchestrator-db

  recognizer:
    container_name: recognizer
    image: nekromant322/overmoney:recognizer
    ports:
      - '8080:8080'
    environment:
      RECOGNIZER_DB_USER: ${RECOGNIZER_DB_USER}
      RECOGNIZER_DB_PASSWORD: ${RECOGNIZER_DB_PASSWORD}
      RECOGNIZER_DB_HOST: ${RECOGNIZER_DB_HOST}
      RECOGNIZER_DB_PORT: ${RECOGNIZER_DB_PORT}
    depends_on:
      - recognizer-db

  telegram-bot:
    container_name: telegram-bot
    image: nekromant322/overmoney:telegram_bot
    ports:
      - '8082:8082'
    environment:
      TELEGRAM_BOT_DB_USER: ${TELEGRAM_BOT_DB_USER}
      TELEGRAM_BOT_DB_PASSWORD: ${TELEGRAM_BOT_DB_PASSWORD}
      TELEGRAM_BOT_DB_HOST: ${TELEGRAM_BOT_DB_HOST}
      TELEGRAM_BOT_DB_PORT: ${TELEGRAM_BOT_DB_PORT}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    depends_on:
      - telegram-bot-db