version: '3.1'

services:
  orchestrator-db:
    container_name: orchestrator-db
    image: postgres:14.1-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: ${ORCHESTRATOR_DB_USER}
      POSTGRES_PASSWORD: ${ORCHESTRATOR_DB_PASSWORD}
      POSTGRES_DB: orchestrator-db
    restart: always
  recognizer-db:
    container_name: recognizer-db
    image: postgres:14.1-alpine
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: ${RECOGNIZER_DB_USER}
      POSTGRES_PASSWORD: ${RECOGNIZER_DB_PASSWORD}
      POSTGRES_DB: recognizer-db
    restart: always
  eureka:
    container_name: eureka
    image: nekromant322/overmoney:eureka
    ports:
      - '8761:8761'
  orchestrator:
    container_name: orchestrator
    image: nekromant322/overmoney:orchestrator
    ports:
      - '8081:8081'
    environment:
      ORCHESTRATOR_DB_USER: ${ORCHESTRATOR_DB_USER}
      ORCHESTRATOR_DB_PASSWORD: ${ORCHESTRATOR_DB_PASSWORD}
    depends_on:
      - orchestrator-db
  recognizer:
    container_name: recognizer
    image: nekromant322/overmoney:recognizer
    ports:
      - '8080:8080'
    environment:
      RECOGNIZER_DB_USER: ${RECOGNIZER_DB_USER}
      RECOGNIZER_DB_PASSWORD: ${RECOGNIZER_DB_PASSWORD}
    depends_on:
      - recognizer-db