version: '3.1'

services:
  orchestrator-db:
    container_name: orchestrator-db
    image: postgres:14.1-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orchestrator-db
    restart: always

  telegram-bot-db:
    container_name: telegram-bot-db
    image: postgres:14.1-alpine
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: telegram-bot-db
    restart: always

  eureka:
    container_name: eureka
    build:
      context: .
      dockerfile: eureka_service/Dockerfile
    ports:
      - '8761:8761'
    environment:
      _JAVA_OPTIONS: -Xmx256m

  orchestrator:
    container_name: orchestrator
    build:
      context: .
      dockerfile: orchestrator_service/Dockerfile
    ports:
      - '8081:8081'
    environment:
      _JAVA_OPTIONS: -Xmx256m
      ORCHESTRATOR_DB_USER: postgres
      ORCHESTRATOR_DB_PASSWORD: postgres
      ORCHESTRATOR_DB_HOST: orchestrator-db
      ORCHESTRATOR_DB_PORT: 5432
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_BOT_NAME: ${TELEGRAM_BOT_NAME}
      JWT_ACCESS_KEY: 4LKiGdX0aJhBdx5wFH5cs8v6HnGIUyhDn7BeoLqJ4UEixTGOT3CYKg6YrzS32K5hMlVdstATeliyxhRH0eaU6A==
      JWT_REFRESH_KEY: 5LKiGdX0aJhBdx5wFH5cs8v6HnGIUyhDn7BeoLqJ4UEixTGOT3CYKg6YrzS32K5hMlVdstATeliyxhRH0eaU6A==
    depends_on:
      - orchestrator-db

  recognizer:
    container_name: recognizer
    build:
      context: .
      dockerfile: recognizer_service/Dockerfile
    ports:
      - '8080:8080'
    environment:
      _JAVA_OPTIONS: -Xmx256m
      WIT_AI_TOKEN: ${WIT_AI_TOKEN}

  telegram-bot:
    container_name: telegram-bot
    build:
      context: .
      dockerfile: telegram_bot_service/Dockerfile
    ports:
      - '8082:8082'
    environment:
      _JAVA_OPTIONS: -Xmx256m
      TELEGRAM_BOT_DB_USER: postgres
      TELEGRAM_BOT_DB_PASSWORD: postgres
      TELEGRAM_BOT_DB_HOST: telegram-bot-db
      TELEGRAM_BOT_DB_PORT: 5432
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_BOT_NAME: ${TELEGRAM_BOT_NAME}
      ORCHESTRATOR_HOST: ${ORCHESTRATOR_HOST}
    depends_on:
      - telegram-bot-db

  wit-ai-go-proxy:
    container_name: wit-ai-go-proxy
    build: wit_ai_go_proxy
    restart: unless-stopped
    ports:
      - '3333:3333'
    environment:
      WIT_AI_TOKEN: ${WIT_AI_TOKEN}