version: '3.1'

services:

  orchestrator-db:
    container_name: orchestrator-db
    image: postgres:14.1-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: ${ORCHESTRATOR_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${ORCHESTRATOR_DB_PASSWORD:-postgres}
      POSTGRES_DB: orchestrator-db
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: 50m

  telegram-bot-db:
    container_name: telegram-bot-db
    image: postgres:14.1-alpine
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: ${TELEGRAM_BOT_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${TELEGRAM_BOT_DB_PASSWORD:-postgres}
      POSTGRES_DB: telegram-bot-db
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: 50m

  eureka:
    container_name: eureka
    image: nekromant322/overmoney:eureka
    restart: unless-stopped
    ports:
      - '8761:8761'
    environment:
      _JAVA_OPTIONS: -Xmx256m
      SPRING_APPLICATION_PROFILE: ${SPRING_APPLICATION_PROFILE}
    logging:
      driver: "json-file"
      options:
        max-size: 50m

  orchestrator:
    container_name: orchestrator
    image: nekromant322/overmoney:orchestrator
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      _JAVA_OPTIONS: -Xmx256m
      ORCHESTRATOR_DB_USER: ${ORCHESTRATOR_DB_USER}
      ORCHESTRATOR_DB_PASSWORD: ${ORCHESTRATOR_DB_PASSWORD}
      ORCHESTRATOR_DB_HOST: ${ORCHESTRATOR_DB_HOST}
      ORCHESTRATOR_DB_PORT: ${ORCHESTRATOR_DB_PORT}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_BOT_NAME: ${TELEGRAM_BOT_NAME}
      JWT_ACCESS_KEY: ${JWT_ACCESS_KEY}
      JWT_REFRESH_KEY: ${JWT_REFRESH_KEY}
      SPRING_APPLICATION_PROFILE: ${SPRING_APPLICATION_PROFILE}
      INTERNAL_KEY_HEADER: ${INTERNAL_KEY_HEADER}
    depends_on:
      - orchestrator-db
    logging:
      driver: "json-file"
      options:
        max-size: 50m

  recognizer:
    container_name: recognizer
    image: nekromant322/overmoney:recognizer
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      _JAVA_OPTIONS: -Xmx512m
      SPRING_APPLICATION_PROFILE: ${SPRING_APPLICATION_PROFILE}
      WIT_AI_TOKEN: ${WIT_AI_TOKEN}
      INTERNAL_KEY_HEADER: ${INTERNAL_KEY_HEADER}
    logging:
      driver: "json-file"
      options:
        max-size: 50m

  telegram-bot:
    container_name: telegram-bot
    image: nekromant322/overmoney:telegram-bot
    restart: unless-stopped
    ports:
      - '8082:8082'
    environment:
      _JAVA_OPTIONS: -Xmx256m
      TELEGRAM_BOT_DB_USER: ${TELEGRAM_BOT_DB_USER}
      TELEGRAM_BOT_DB_PASSWORD: ${TELEGRAM_BOT_DB_PASSWORD}
      TELEGRAM_BOT_DB_HOST: ${TELEGRAM_BOT_DB_HOST}
      TELEGRAM_BOT_DB_PORT: ${TELEGRAM_BOT_DB_PORT}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_BOT_NAME: ${TELEGRAM_BOT_NAME}
      SPRING_APPLICATION_PROFILE: ${SPRING_APPLICATION_PROFILE}
      ORCHESTRATOR_HOST: ${ORCHESTRATOR_HOST}
      INTERNAL_KEY_HEADER: ${INTERNAL_KEY_HEADER}
    depends_on:
      - telegram-bot-db
    logging:
      driver: "json-file"
      options:
        max-size: 50m

  wit-ai-go-proxy:
    container_name: wit-ai-go-proxy
    image: nekromant322/overmoney:wit-ai-go-proxy
    restart: unless-stopped
    ports:
      - '3333:3333'
    environment:
      WIT_AI_TOKEN: ${WIT_AI_TOKEN}
    logging:
      driver: "json-file"
      options:
        max-size: 50m

  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    command:
      - '--storage.tsdb.retention.time=10d'
    logging:
      driver: "json-file"
      options:
        max-size: 50m
