  server:
    port: 8080

  wit-ai:
    secret:
      url: https://api.wit.ai/speech
      token: ${WIT_AI_TOKEN}
      version: 20230215
    connection:
      charset: UTF-8
      method: POST
      authProperty: Authorization
      contentTypeProperty: Content-Type
      contentTypeValue: audio/wav
      paramSeparator: "?"
      versionParam: v=%s

  spring:
    application:
      name: recognizer-service

    profiles:
      active: ${SPRING_APPLICATION_PROFILE:dev}

  eureka:
    client:
      serviceUrl:
        defaultZone: http://eureka:8761/eureka

  logging:
    level:
      org.zalando.logbook: TRACE

  management:
    endpoints:
      web:
        exposure:
          include: "*"