apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orchestrator-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sa-orchestrator
                port:
                  number: 8081