apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-orchestrator
  labels:
    app: sa-orchestrator
spec:
  selector:
    matchLabels:
      app: sa-orchestrator
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sa-orchestrator
    spec:
      containers:
        - image: nekromant322/overmoney-orchestrator:latest
          imagePullPolicy: Always
          name: sa-orchestrator
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          env:
            - name: SPRING_APPLICATION_PROFILE
              value: "prod"
            - name: TELEGRAM_BOT_TOKEN
              value: "7842052634:AAFMbmCMzbA2mmymNPQIW_wyZ44dxEdQd60"
            - name: TELEGRAM_BOT_NAME
              value: "OverrideTestBot"
            - name: INTERNAL_KEY_HEADER
              value: "X-INTERNAL-KEY"
            - name: JWT_ACCESS_KEY
              value: "qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w"
            - name: JWT_REFRESH_KEY
              value: "zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg=="
            - name: ORCHESTRATOR_DB_HOST
              value: "postgres-orchestrator-service"
            - name: ORCHESTRATOR_DB_PORT
              value: "5432"
            - name: ORCHESTRATOR_DB_USER
              value: "postgres"
            - name: ORCHESTRATOR_DB_PASSWORD
              value: "postgres"
          ports:
            - containerPort: 8080