apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-telegram-bot
  labels:
    app: sa-telegram-bot
spec:
  selector:
    matchLabels:
      app: sa-telegram-bot
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sa-telegram-bot
    spec:
      containers:
        - image: nekromant322/overmoney-telegram-bot:latest
          imagePullPolicy: Always
          name: sa-telegram-bot
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "1Gi"
          env:
            - name: SPRING_APPLICATION_PROFILE
              value: "prod"
            - name: ORCHESTRATOR_HOST
              value: "https://overmoney.online/overmoney" # но это неточно
            - name: INTERNAL_KEY_HEADER
              value: "X-INTERNAL-KEY"
            - name: TELEGRAM_BOT_NAME
              value: "OverrideTestBot"
            - name: TELEGRAM_BOT_TOKEN
              value: "7842052634:AAFMbmCMzbA2mmymNPQIW_wyZ44dxEdQd60"
            - name: TELEGRAM_BOT_DB_HOST
              value: "postgres-telegram-bot-service"
            - name: TELEGRAM_BOT_DB_PORT
              value: "5432"
            - name: TELEGRAM_BOT_DB_USER
              value: "postgres"
            - name: TELEGRAM_BOT_DB_PASSWORD
              value: "postgres"
          ports:
            - containerPort: 8080