apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-telegram-bot
  labels:
    app: sa-telegram-bot
spec:
  selector:
    matchLabels:
      app: sa-telegram-bot
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sa-telegram-bot
    spec:
      containers:
        - image: nekromant322/overmoney-telegram-bot:latest
          imagePullPolicy: Always
          name: sa-telegram-bot
          resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "256Mi"
          env:
            - name: SPRING_APPLICATION_PROFILE
              value: "prod"
            - name: INTERNAL_KEY_HEADER
              value: "{{ INTERNAL_KEY_HEADER }}"
            - name: TELEGRAM_BOT_NAME
              value: "OverMoneyBot"
            - name: TELEGRAM_BOT_TOKEN
              value: "{{ TELEGRAM_BOT_TOKEN }}"
            - name: TELEGRAM_BOT_DB_HOST
              value: "{{ TELEGRAM_BOT_DB_HOST }}"
            - name: TELEGRAM_BOT_DB_PORT
              value: "{{ TELEGRAM_BOT_DB_PORT }}"
            - name: TELEGRAM_BOT_DB_USER
              value: "{{ TELEGRAM_BOT_DB_USER }}"
            - name: TELEGRAM_BOT_DB_PASSWORD
              value: "{{ TELEGRAM_BOT_DB_PASSWORD }}"
          ports:
            - containerPort: 8080