  server:
    port: 8087

  spring:
    application:
      name: invest-service

    profiles:
      active: ${SPRING_APPLICATION_PROFILE:dev}

  eureka:
    client:
      serviceUrl:
        defaultZone: http://eureka:8761/eureka

  logging:
    level:
      org.zalando.logbook: TRACE

  management:
    endpoints:
      web:
        exposure:
          include: health,prometheus
    metrics:
      export:
        prometheus:
          enabled: true
      distribution:
        percentiles-histogram:
          "[http.server.requests]": true

  authorization-header:
    header-value: ${INTERNAL_KEY_HEADER:X-INTERNAL-KEY}

  mask-log-spring-boot-starter:
    maskedFields:
      - x-internal-key
      - investAccountId
      - token
      - tinkoffAccountId
      - favoriteAccountId
