  spring:
    application:
      name: eureka_service

  server:
    port: 8761

  eureka:
    client:
      register-with-eureka: false
      fetch-registry: false

  logging:
    level:
      org.zalando.logbook: TRACE

  management:
    endpoints:
      web:
        exposure:
          include: "*"