name: Generate and commit badges

on:
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN_FOR_ACTION }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B verify

      - name: Generate Coverage Badges for Orchestrator
        id: jacocoOrchestrator
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: orchestrator_service/target/jacoco-report/jacoco.csv
          coverage-badge-filename: jacoco_orchestrator.svg
          coverage-label: coverage (Orchestrator)

      - name: Generate Coverage Badges for Recognizer
        id: jacocoRecognizer
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: recognizer_service/target/jacoco-report/jacoco.csv
          coverage-badge-filename: jacoco_recognizer.svg
          coverage-label: coverage (Recognizer)

      - name: Generate Coverage Badges for Telegram Bot
        id: jacocoTelegramBot
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: telegram_bot_service/target/jacoco-report/jacoco.csv
          coverage-badge-filename: jacoco_telegram_bot.svg
          coverage-label: coverage (Telegram Bot)

      - name: Commit the badge (if it changed)
        run: |
          if [[ `git status --porcelain` ]]; then
           git config --global user.name 'nekromant322'
           git config --global user.email 'nekromant322@users.noreply.github.com'
           git add -A
           git commit -m "JaCoCo coverage badges"
           git push
          fi