  name: Build & Deploy

  on:
    push:
      branches:
        - master

  jobs:
  build_and_push_image:
    name: Push image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Eureka Build and Push to Dockerhub
        uses: docker/build-push-action@v2
        with:
          context: ./eureka_server
          file: ./eureka_server/Dockerfile
          push: true
          tags: nekromant322/overmoney:eureka

      - name: Orchestrator Build and Push to Dockerhub
        uses: docker/build-push-action@v2
        with:
          context: ./orchestrator_service
          file: ./orchestrator_service/Dockerfile
          push: true
          tags: nekromant322/overmoney:orchestrator

      - name: Recognizer Build and Push to Dockerhub
        uses: docker/build-push-action@v2
        with:
          context: ./recognizer_service
          file: ./recognizer_service/Dockerfile
          push: true
          tags: nekromant322/overmoney:recognizer

    deploy:
      name: Deploy
      runs-on: ubuntu-latest
      needs: [build_and_push_image]
      steps:
        - name: Connect with SSH and Deploy
          uses: appleboy/ssh-action@v0.1.8
          with:
            host: 194.87.237.176
            username: ${{ secrets.SSH_USER }}
            password: ${{ secrets.SSH_PASSWORD }}
            script: |
              echo RECOGNIZER_DB_USER = ${{ secrets.RECOGNIZER_DB_USER }} > overmoney-env.txt
              echo RECOGNIZER_DB_PASSWORD = ${{ secrets.RECOGNIZER_DB_PASSWORD }} >> overmoney-env.txt
              echo ORCHESTRATOR_DB_PASSWORD = ${{ secrets.ORCHESTRATOR_DB_PASSWORD }} >> overmoney-env.txt
              echo ORCHESTRATOR_DB_PASSWORD = ${{ secrets.ORCHESTRATOR_DB_PASSWORD }} >> overmoney-env.txt
            
              echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker stop eureka
              echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker stop recognizer
              echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker stop orchestrator
              echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker rm eureka
              echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker rm recognizer
              echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker rm orchestrator
              echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker rmi nekromant322/overmoney:eureka
              echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker rmi nekromant322/overmoney:recognizer
              echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker rmi nekromant322/overmoney:orchestrator
              echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker compose --env-file overmoney-env.txt up -d docker-compose
              echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker ps -a  
              rm overmoney-env.txt