name: nginx

on:
  push:
    branches:
      - fix/OV-29

jobs:
  rewrite_nginx:
    name: Copy nginx files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy nginx.conf and /sites-enabled via SSH
        uses: appleboy/scp-action@master
        with:
          host: overridetech.ru
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "nginx/*"
          target: "/home/${{ secrets.SSH_USER }}"
          overwrite: true

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [rewrite_nginx]
    steps:
      - name: Connect with SSH and Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: overridetech.ru
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S cp -r '/home/${{ secrets.SSH_USER }}/nginx'/* /etc/nginx
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S systemctl restart nginx

