name: Build & Push & Deploy to k8s cluster

on:
  push:
    branches:
      - release


jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      recognizer: ${{ steps.filter.outputs.recognizer }}
      orchestrator: ${{ steps.filter.outputs.orchestrator }}
      telegram-bot: ${{ steps.filter.outputs.telegram-bot }}
      invest: ${{ steps.filter.outputs.invest }}
      wit-ai-go-proxy: ${{ steps.filter.outputs.wit-ai-go-proxy }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            recognizer:
              - 'recognizer_service/**'
            orchestrator:
              - 'orchestrator_service/**'
            telegram-bot:
              - 'telegram_bot_service/**'
            invest:
              - 'invest_service/**'
            wit-ai-go-proxy:
              - 'wit_ai_go_proxy/**'
  build-and-push-images:
    name: Build & Push images to DockerHub
    runs-on: ubuntu-latest
    needs: detect-changes
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Orchestrator Build and Push to Dockerhub
#        if: ${{ needs.paths-filter.outputs.orchestrator == 'true' }}
        uses: docker/build-push-action@v2
        with:
          file: /orchestrator_service/Dockerfile
          push: true
          tags: nekromant322/overmoney-orchestrator

      - name: Recognizer Build and Push to Dockerhub
#        if: ${{ needs.paths-filter.outputs.recognizer == 'true' }}
        uses: docker/build-push-action@v2
        with:
          file: /recognizer_service/Dockerfile
          push: true
          tags: nekromant322/overmoney-recognizer

      - name: Telegram Bot Build and Push to Dockerhub
#        if: ${{ needs.paths-filter.outputs.telegram-bot == 'true' }}
        uses: docker/build-push-action@v2
        with:
          file: /telegram_bot_service/Dockerfile
          push: true
          tags: nekromant322/overmoney-telegram-bot

      - name: Invest Build and Push to Dockerhub
#        if: ${{ needs.paths-filter.outputs.invest == 'true' }}
        uses: docker/build-push-action@v2
        with:
          file: /invest_service/Dockerfile
          push: true
          tags: nekromant322/overmoney-invest

      - name: Wit ai go proxy Build and Push to Dockerhub
#        if: ${{ needs.paths-filter.outputs.wit-ai-go-proxy == 'true' }}
        uses: docker/build-push-action@v2
        with:
          file: /wit_ai_go_proxy/Dockerfile
          push: true
          tags: nekromant322/overmoney-wit-ai-go-proxy
#  k8s-rollout-restart:
#    name: Run cluster updates on actual manifests
#    if: ${{ needs.paths-filter.outputs.nginx == 'true' }}
#    uses: appleboy/scp-action@master
#    with:
#      host: 195.133.49.108
#      username: github
#      key: ${{ secrets.SSH_PRIVATE_KEY_GITHUB_USER }}
#      port: 22
#      source: "resource-manifest/*"
#      target: "/home/${{ secrets.SSH_USER }}"
#      overwrite: true
  k8s-rollout-restart:
    name: Copy k8s manifests by ssh
    runs-on: ubuntu-latest
    needs: build-and-push-images
    steps:
      - uses: actions/checkout@v4
      - name: copy file via ssh private key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 195.133.49.108
          username: github
          key: ${{ secrets.SSH_PRIVATE_KEY_GITHUB_USER }}
          passphrase : ${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE_GITHUB_USER }}
          port: 22
          source: "resource-manifest/*"
          target: "/home/${{ secrets.SSH_USER }}"
          overwrite: true
#  inject-secrets:
#    name: Inject secrets to yaml files
#    uses: none0nfg/yaml-secrets-injector@v0.0.1
#    with:
#      inject_files: |-
#        resource-manifest/sa-recognizer-deployment.yaml
#        path/to/file2.yaml
#      secrets: ${{ toJSON(secrets) }} # It would contain all your repository secrets in json





#todo доделать инжекты и копирование манифестов, перенести вероятно в другой шаг
#todo попробовать профиль прод и подсунуть креды
#kubectl rollout restart deployment "depName"
#kubectl rollout restart deployment sa-recognizer
