name: Run tests

on:
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
<<<<<<<<< Temporary merge branch 1
          distribution: 'temurin'
=========
          distribution: 'corretto'
          cache: 'maven'
>>>>>>>>> Temporary merge branch 2

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Test
        run: mvn verify